#kibana: Dockerfile
FROM docker.elastic.co/kibana/kibana-oss:6.2.4 
RUN bin/kibana-plugin install https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/6.2.4-15/search-guard-kibana-plugin-6.2.4-15.zip
#RUN bin/kibana-plugin install https://github.com/wtakase/kibana-own-home/releases/download/v6.2.4/own_home-6.2.4.zip
